spring:
  application:
    name: spring-cloud-service-admin
  #zipkin服务追踪
  zipkin:
    base-url: http://localhost:9411
  #admin服务监控配置
  boot:
    admin:
      client:
        url: http://localhost:8084
server:
  port: 8763

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/