spring:
  application:
    name: spring-cloud-eureka
  #zipkin服务追踪
  zipkin:
    base-url: http://localhost:9411
  #admin服务监控配置
  boot:
    admin:
      client:
        url: http://localhost:8084
server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    #eureka服务端模式
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/