spring:
  application:
    name: spring-cloud-zipkin
  #admin服务监控配置
  boot:
    admin:
      client:
        url: http://localhost:8084
##zipkin默认端口9411
server:
  port: 9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
##2.10.1新配置
management:
  metrics:
    web:
      server:
        auto-time-requests: false